//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierServiceManagement
{


    public partial class CourierBooking
    
        {
            protected global::System.Web.UI.WebControls.TextBox txtSender;
            protected global::System.Web.UI.WebControls.TextBox txtSenderAddress;
            protected global::System.Web.UI.WebControls.TextBox txtReceiver;
            protected global::System.Web.UI.WebControls.TextBox txtReceiverAddress;
            protected global::System.Web.UI.WebControls.TextBox txtCity;
            protected global::System.Web.UI.WebControls.TextBox txtPincode;
            protected global::System.Web.UI.WebControls.TextBox txtWeight;
            protected global::System.Web.UI.WebControls.TextBox txtKM;

            protected global::System.Web.UI.WebControls.DropDownList ddlService;
            protected global::System.Web.UI.WebControls.DropDownList ddlPayment;

            protected global::System.Web.UI.WebControls.Label lblAmount;
            protected global::System.Web.UI.WebControls.Button btnBook;



            protected global::System.Web.UI.WebControls.Label lblMessage;
            protected global::System.Web.UI.WebControls.PlaceHolder phReceipt;

            protected global::System.Web.UI.WebControls.Panel pnlCOD;
            protected global::System.Web.UI.WebControls.Panel pnlUPI;
            protected global::System.Web.UI.WebControls.Panel pnlQR;

            protected global::System.Web.UI.WebControls.TextBox txtSenderPhone;
            protected global::System.Web.UI.WebControls.TextBox txtReceiverPhone;
        }
    }
